package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.User;
import solid5ive.cams.data.entities.UserAccount;

/**
 * No concrete class define for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface AccountRepository extends JpaRepository<UserAccount, Integer> {
    public UserAccount findByUser(User user);
}
