package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.ContactType;
import solid5ive.cams.data.entities.User;
import solid5ive.cams.data.entities.UserContact;

import java.util.List;

/**
 * No concrete class define for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface ContactRepository extends JpaRepository<UserContact, Integer> {
    public List<UserContact> findByUser(User user);
    public List<UserContact> findByUserAndType(User user, ContactType contactType);
}
