package solid5ive.cams.data.repositories;

import org.joda.time.DateTime;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import solid5ive.cams.data.entities.Menu;
import solid5ive.cams.data.entities.Stall;

import java.util.List;

/**
 * No concrete class define for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface MenuRepository extends JpaRepository<Menu, Integer> {
    public List<Menu> findByStall(Stall stall);
    @Query("select m from Menu m where m.stall = ?1 and m.lastModified > ?2")
    public List<Menu> findUpdatedByStall(Stall stall, DateTime refDateTime);
}
