package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.MenuReference;

/**
 * No concrete class define for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface MenuRefRepository extends JpaRepository<MenuReference, Integer> {
}
