package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.Order;
import solid5ive.cams.data.entities.Stall;

import java.util.List;
import org.joda.time.DateTime;
import org.springframework.data.jpa.repository.Query;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface OrderRepository extends JpaRepository<Order, Integer> {
    public List<Order> findByStall(Stall stall);
    @Query("select o from Order o where o.stall = ?1 and ?2 <= o.timestamp and ?3 >= o.timestamp")
    public List<Order> findByStallAndPeriod(Stall stall, DateTime begin, DateTime end);
}
