package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.UserPermission;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface PermissionRepository extends JpaRepository<UserPermission, Integer> {
}
