package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.UserRole;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface RoleRepository extends JpaRepository<UserRole, Integer> {
    public UserRole findByRole(String role);
}
