package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import solid5ive.cams.data.entities.Canteen;
import solid5ive.cams.data.entities.Stall;
import solid5ive.cams.data.entities.User;

import java.util.List;
import org.springframework.data.jpa.repository.Query;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface StallRepository extends JpaRepository<Stall, Integer> {
    public List<Stall> findByOwner(User user);
    public List<Stall> findByCanteen(Canteen canteen);
    public List<Stall> findByCanteenAndLotNumber(Canteen canteen, String lotNumber);
    @Query("select s from Stall s where s.canteen = ?1 and s.foodStyle != null and s.foodStyle != '' and s.foodStyle = ?2")
    public List<Stall> findByFoodStyleInCanteen(Canteen canteen, String foodStyle);
}
