/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solid5ive.cams.data.repositories;

import java.util.List;
import org.joda.time.DateTime;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import solid5ive.cams.data.entities.BalanceTransaction;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface TransactionRepository extends JpaRepository<BalanceTransaction, Integer>{
    
    @Query("select bt from BalanceTransaction bt where datetime >= ?1 and datetime <= ?2")
    public List<BalanceTransaction> findByPeriod(DateTime begin, DateTime end);
}
