package solid5ive.cams.data.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import solid5ive.cams.data.entities.User;

import java.util.Set;

/**
 * No concrete class defined for this interface, 
 * the database access code is generated by Spring library at runtime.
 * 
 * @author Poh Shie Liang
 */
public interface UserRepository extends JpaRepository<User, String> {
    public Set<User> findByName(String name);
    @Query("select distinct u from User u join u.roles r where r.role = ?1")
    public Set<User> findByRole(String role);
}
